# .github/workflows/cd.yml
name: CD

on:
  push:
    branches:
      - main  # Trigger on main branch pushes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitOps repo
      uses: actions/checkout@v2
      with:
        repository: your-username/your-gitops-repo  # Link to GitOps repo
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update Kubernetes manifest with new image
      run: |
        sed -i "s|image:.*|image: your-username/your-app:${{ github.sha }}|" k8s/deployment.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add k8s/deployment.yaml
        git commit -m "Update image to ${{ github.sha }}"
        git push
