# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main  # Trigger on main branch pushes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Build Docker image
      run: docker build -t your-username/your-app:${{ github.sha }} .

    - name: Push Docker image
      run: docker push your-username/your-app:${{ github.sha }}
      
    - name: Update Kubernetes manifests
      run: |
        sed -i "s|image:.*|image: your-username/your-app:${{ github.sha }}|" k8s/deployment.yaml
      # Commit the updated manifest file if desired
